### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by L1ck** [L1ck/furima-32546#10]
# 自身のフリマアプリのURL（本番環境）
https://furima-32546.herokuapp.com/
# Basic認証のIDとパスワード
ID: admin
pass: 2222
#出品者用のメールアドレスとパスワード
メールアドレス: syuppinsya@gmail.com
pass: syuppinsya1
#購入者用のメールアドレスとパスワード
メールアドレス: kounyusya@gmail.com
pass:kounyusya1
#購入用カードの番号・期限・セキュリティコード
カード番号:5105105105105100
カード期限:03/33
セキュリティ番号:123

お手数おかけしますがご確認よろしくお願いいたします。

**Comment by mo1015** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]

- [x] **ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると、トップページに遷移するようにしましょう**
-現状エラーページに遷移します

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by L1ck** [comment]
ご確認ありがとうございます。
ログイン状態の出品者が、URLを直接入力して自身の出品した商品購入ページに遷移しようとすると、エラーが出るとのことですが、自分の本番環境では正常に動作していました。再度ご確認いただけますでしょうか？

**Comment by mo1015** [comment]
再提出ありがとうございます！
再度挙動確認させて頂いたところ、やはりエラー画面に遷移してしまいました。
<img width="1052" alt="スクリーンショット 2021-01-22 11 29 28" src="https://user-images.githubusercontent.com/62644781/105437944-62b01c00-5ca5-11eb-8562-9ad3acdee97b.png">

恐れ入りますが、デプロイを含め再度、本番環境で実装できているか確認をお願いできますでしょうか。
よろしくお願い致します。

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by L1ck** [comment]
デプロイを含め再度、本番環境で実装できているか確認しましたが正常に動作しているみたいです；；
こちら動作画面のGIFになります
https://i.gyazo.com/d75247295d498ffd7c70a73d7a51f8e5.gif

**Comment by mo1015** [comment]
動作画面の添付、詳細のご連絡ありがとうございます。
大変失礼いたしました。修正依頼文章に誤りがございました。

下記が正しい修正箇所となります。
また、新たに修正をお願いしたい箇所がございましたので、お伝えさせていただきます。

[修正箇所]

- [ ] **ログイン状態のユーザーが、URLを直接入力して「売却済み商品」の商品購入ページへ遷移しようとすると、トップページに遷移するようにしましょう**


- [ ] **出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう**
-現状、編集画面に遷移できてしまいます


[補足]
商品詳細ページで「配送料の負担」が正しく表示されていないため、可能であれば修正しましょう
-「2」と表示されています

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
動作画面の添付、詳細のご連絡ありがとうございます。
大変失礼いたしました。修正依頼文章に誤りがございました。

下記が正しい修正箇所となります。
また、新たに修正をお願いしたい箇所がございましたので、お伝えさせていただきます。

[修正箇所]

- [x] **ログイン状態のユーザーが、URLを直接入力して「売却済み商品」の商品購入ページへ遷移しようとすると、トップページに遷移するようにしましょう**


- [x] **出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう**
-現状、出品者が編集画面に遷移できてしまいます

- [x] **商品出品ページにて、価格の範囲が、¥300~¥9,999,999の間としましょう**
　-9,999,999のときに出品できません

[補足]
商品詳細ページで「配送料の負担」が正しく表示されていないため、可能であれば修正しましょう
-「2」と表示されています

修正でき次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by L1ck** [comment]
修正しました！
再度ご確認お願いします

**Comment by naru6117** [comment]
ご提出ありがとうございます！
挙動確認させて頂いたところ、「**商品出品ページにて、価格の範囲が、¥300~¥9,999,999の間としましょう**」については修正が確認できました(^^)！
その他に以下の不備が見受けられましたので修正をお願いします！

### [修正依頼箇所]

- [x] **必要な情報を適切に入力すると、商品の購入ができるようにしましょう！**
現状、「購入画面に進む」ボタンを押すとエラー画面になってしまい、購入作業ができませんでした
<img width="944" alt="スクリーンショット 2021-01-22 12 49 02" src="https://user-images.githubusercontent.com/49669977/105444129-a1979f00-5cb0-11eb-9e2a-c5e0bfddcd6a.png">

**上記のため、購入に関する挙動と、下記の項目に関しては挙動確認が行えないため、次回以降に確認いたします！**
`出品者・出品者以外にかかわらず、ログイン状態のユーザーが、URLを直接入力して売却済み商品の商品情報編集ページへ遷移しようとすると、トップページに遷移するようにしましょう`
`ログイン状態のユーザーが、URLを直接入力して「売却済み商品」の商品購入ページへ遷移しようとすると、トップページに遷移するようにしましょう`

修正ができましたら、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by L1ck** [comment]
お手数おかけして申し訳ありません。
その点も修正させていただきました！
ご確認お願いします

**Comment by mutorisa** [comment]
@L1ck さん、再度ご提出ありがとうございます‼︎
以下については修正の確認ができました✨
`必要な情報を適切に入力すると、商品の購入ができるようにしましょう！`

ただし、新たに修正が必要な箇所がございました。
以下のご確認をお願いします！

**[修正依頼箇所]**

- [x] **【商品購入画面】にて入力に問題がある状態で購入ボタンが押されたら、購入ページに戻りエラーメッセージが表示されるよう実装しましょう**
（現在は以下添付画像のようなエラーページに遷移される状態です）
<img width="600" alt="スクリーンショット 2021-01-22 14 05 10" src="https://user-images.githubusercontent.com/65144927/105449518-e5dc6c80-5cbb-11eb-8e0f-71ef56f70e2f.png">


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by L1ck** [comment]
修正しました
お願いします

**Comment by mutorisa** [comment]
再度ご提出ありがとうございます！
以下修正の確認ができました✨
`【商品購入画面】にて入力に問題がある状態で購入ボタンが押されたら、購入ページに戻りエラーメッセージが表示されるよう実装しましょう`

１点追加で修正が必要な箇所がございました。失礼いたしました。
以下のご確認をお願い致します。

**[修正依頼箇所]**
**商品購入時、PAY.JPのテストモード用カード情報以外のカード情報を入力した場合は、商品が購入できないよう実装しましょう。**
※Issue及び、最終課題説明文のカード情報の訂正もお願い致します。

[参考]
`最終課題補足カリキュラム`
`〜クレジットカード決済機能ミニアプリを作成しよう〜`

修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by L1ck** [comment]
確認ありがとうございます
trelloの実装条件に見受けられないように思うのですが、、、

**Comment by L1ck** [comment]
すみません勘違いでした、、、

**Comment by mutorisa** [comment]
@L1ck さん、コメントありがとうございます！
以下の通りTrelloに記載がございますのでご確認をお願い致します。

**[商品購入機能]**
**#実装条件**　
`クレジットカード情報は必須であり、正しいクレジットカードの情報でないときは決済できないこと
`

**#補足情報**
`クレジットカードでの決済機能は、以下のカリキュラムを参考にして、PAY.JPを使用すること。`
`最終課題補足カリキュラムLesson1「クレジット決済機能ミニアプリを作成しよう」
`


修正が完了しましたら、再度以下の最終課題完了報告フォームのご提出をお願いします。
※新しいissueを作っていただく必要はございません。
https://forms.gle/dYuR1wjeHepbEhU7A
